name: GildorymUnconsciousness
author: Lucariatias
version: 2.0.2
main: com.gildorymrp.unconsciousness.GildorymUnconsciousness
depend: [GildorymAPI]
commands:
    wake:
        description: Forcefully wakes a player from unconsciousness
        usage: /<command> [player]
permissions:
    gildorym.command.wake:
        description: Allows you to forcefully wake players
        default: op